resources:
- manifests/namespace.yml

- manifests/persistent_volume.yml
- manifests/persistent_volume_claim.yml

- manifests/database/config_map_db.yml
- manifests/database/secret.yml
- manifests/database/statefulset.yml
- manifests/database/service.yml

- manifests/deployment.yml
- manifests/service.yml

- manifests/ingress.yml

images:
  - name: PROJECT/IMAGE
    newName: jamesho287/kube-ex1-02:v0.7