apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - manifests/namespace.yml
- manifests/database/storageclass_local_path.yml

- manifests/database/config_map_db.yml
- manifests/database/secret.yml
- manifests/database/statefulset.yml
- manifests/database/service.yml

- manifests/deployment.yml
- manifests/service.yml

# - manifests/horizontal_pod_autoscaler.yml

- manifests/ingress.yml

images:
- name: project-vxy-image
  newName: jamesho287/kube-ex1-02
  newTag: v1.0