resources:
- manifests/namespace.yml

- manifests/database/config_map_db.yml
- manifests/database/secret.yml
- manifests/database/statefulset.yml
- manifests/database/service.yml

- manifests/deployment.yml
- manifests/service.yml

- manifests/horizontal_pod_autoscaler.yml

- manifests/ingress.yml

images:
  - name: project-vxy-image
    newName: some-new-name
    newTag: some-new-tag