apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-config
  namespace: project-vxy
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL PRIMARY KEY,
      content TEXT NOT NULL DEFAULT '',
      is_done BOOLEAN NOT NULL DEFAULT false
    )