apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: project-vxy
type: Opaque
data:
    POSTGRES_DB: ENC[AES256_GCM,data:PvqGFg==,iv:YmuabZYarzAVu8TikvJ1K1YunlPVGmfbjp6PfRiTqtc=,tag:qnOv8AFi+zmlKi4rlPgbsA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:KINFAEKBhScrXFEmjaNm0zgofhY=,iv:Z2O0iWHt7or71qGi5TeMPC6eNZxdPLLuAVUan10x7Yw=,tag:MftpHLqHZxQUQAVg71aV3A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VqFcFJ/fl15SSFFEvyZHcrTktt0=,iv:0jODyni96yp4IdRt3LyNzPC5rEWNeBUL3UwlycWwiuY=,tag:8HIFYeV8R9en04GVLqXsYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mvt0hpd98zp337z0kljfszdfvejk5kjmyms3y2l6jfy3604smsls837g0e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WTN3WEdFSG1rRGM5QXBq
            eXFFc29QTVhNeFlhYmc4dmtIQnlKY3VaZEhzCjcvb2N3em85YWtZSGIyMHlacms3
            dWs1U3NkeEdOeTBuTWNzd3VCaC9ySlkKLS0tIGVZcllPTlZ0SitHeTZIeVUyTzdN
            VlFRbUt5TmRHN2NnR0poejM2a1YybDQK/Md3IbSP/6+8Bt+STyxuvP5PUSfJ/X8W
            S3nDT3SOUCb1tHttugCm35wkjuGLAuZGuCNjadb654sptzBhhCP96w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T23:30:34Z"
    mac: ENC[AES256_GCM,data:lQPimfecWKDeH4F7xc+bR64SEJa0vsISprWfkBd4nR/ADt3KPReKW5bOpGg7MNLgaubnAIJburf/0GV1UfUQhFZR/L2ZKwjBV3CiIymwfvP4huIW4tDyA54IbPtPbBG2YUuaT3VVOzBaKC3u5Umx+rcEUO+fN0ipR1hUFVgRLs0=,iv:qsuGQpABHzjSDucDY5gcg/L23YB9kTNwoYbjzzWpiyk=,tag:b5Dc1EixVWRUiqT0JSbFwg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
