apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: project-vxy
spec:
  replicas: 1
  serviceName: postgres-svc
  selector:
    matchLabels:
      app: postgres-db # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: postgres-db # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: postgres-db
          image: postgres:alpine3.16
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: postgres-secret
          env:
          - name: TZ
            value: Europe/Helsinki
          volumeMounts:
            - name: data
              mountPath: /data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi