apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ex1-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-vxy
  template:
    metadata:
      labels:
        app: project-vxy
    spec:
      volumes:
        - name: shared-bucket
          persistentVolumeClaim:
            claimName: log-app-pv-claim
      containers:
        - name: project-vxy
          image: jamesho287/kube-ex1-02:v0.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-bucket
            mountPath: /usr/src/app/media