apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ex1-02
  namespace: project-vxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-vxy
  template:
    metadata:
      labels:
        app: project-vxy
    spec:
      volumes:
        - name: shared-bucket
          persistentVolumeClaim:
            claimName: project-vxy-pv-claim
      containers:
        - name: backend-container
          image: jamesho287/kube-ex1-02:v0.5
          imagePullPolicy: IfNotPresent
          env:
          - name: BACKEND
            value: "true"
          - name: NS
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
          - secretRef:
              name: postgres-secret
          volumeMounts:
          - name: shared-bucket
            mountPath: /usr/src/app/media
        - name: frontend-container
          image: jamesho287/kube-ex1-02:v0.5
          imagePullPolicy: IfNotPresent
          env:
          - name: BACKEND
            value: "false"
          volumeMounts:
          - name: shared-bucket
            mountPath: /usr/src/app/media