apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ex1-02
  namespace: project-vxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-vxy
  template:
    metadata:
      labels:
        app: project-vxy
    spec:
      volumes:
        - name: shared-bucket
          emptyDir: {}
      containers:
        - name: backend-container
          image: project-vxy-image
          imagePullPolicy: Always
          ports:
          - name: healthz-port
            containerPort: 3300
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 2
            failureThreshold: 5
            httpGet:
              scheme: HTTP
              path: /healthz
              port: healthz-port
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /healthz
              port: healthz-port
          env:
          - name: BACKEND
            value: "true"
          - name: NS
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
          - secretRef:
              name: postgres-secret
          volumeMounts:
          - name: shared-bucket
            mountPath: /usr/src/app/media
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
        - name: frontend-container
          image: project-vxy-image
          imagePullPolicy: Always
          env:
          - name: BACKEND
            value: "false"
          volumeMounts:
          - name: shared-bucket
            mountPath: /usr/src/app/media
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"