apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: project-vxy-hpa
  namespace: project-vxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-ex1-02
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 12
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30