apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: setup-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /project-vxy-backend
        pathType: Prefix
        backend:
          service:
            name: project-vxy-backend-svc
            port:
              number: 8002
      - path: /project-vxy-frontend
        pathType: Prefix
        backend:
          service:
            name: project-vxy-frontend-svc
            port:
              number: 8003
      - path: /log-output
        pathType: Prefix
        backend:
          service:
            name: log-app-svc
            port:
              number: 8004
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: ping-pong-svc
            port:
              number: 8005