apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: setup-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /project-vxy
        pathType: Prefix
        backend:
          service:
            name: project-vxy-svc
            port:
              number: 8082
      - path: /log-output
        pathType: Prefix
        backend:
          service:
            name: log-output-svc
            port:
              number: 8083