apiVersion: v1
kind: Service
metadata:
  name: frontend
  # namespace: project-vxy
spec:
  type: ClusterIP
  selector:
    app: project-vxy
  ports:
    - name: project-vxy-frontend
      port: 8080
      protocol: TCP
      targetPort: 3200
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  # namespace: project-vxy
spec:
  type: ClusterIP
  selector:
    app: project-vxy
  ports:
    - name: project-vxy-backend
      port: 8080
      protocol: TCP
      targetPort: 3300
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-nats
  namespace: prometheus
  labels:
    release: kube-prometheus-stack-1655938402
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  endpoints:
    - interval: 10s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - default