apiVersion: v1
kind: Service
metadata:
  name: project-vxy-backend-svc
spec:
  type: ClusterIP
  selector:
    app: project-vxy
  ports:
    - name: project-vxy-backend
      port: 8002
      protocol: TCP
      targetPort: 3200
---
apiVersion: v1
kind: Service
metadata:
  name: project-vxy-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: project-vxy
  ports:
    - name: project-vxy-frontend
      port: 8003
      protocol: TCP
      targetPort: 3300