name: Production release

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: kube-course
  GKE_ZONE: europe-north1-b
  IMAGE: james/projectvxy

jobs:
  go-production:
    name: Build, publish and deploy
    runs-on: ubuntu-latest

    steps:
      # Set environment for jobs and triggers
      - name: Checkout
        uses: actions/checkout@v3

      # Help deploying to Google Cloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      # Register gcloud as a Docker credential helper
      - run: |-
          gcloud --quiet auth configure-docker

      # Fetch credentials for a running cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Build image
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
            .

      # Push image to Google Container Registry
      - name: Push
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1.6.1

      # Follow kustomize blueprint to initialize the setup
      # Deploy image to the GKE cluster
      - name: Deploy
        run: |-
          kustomize edit set image gcr.io/PROJECT_ID/IMAGE=gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $IMAGE
          kubectl get services -o wide